#!/bin/sh 

URL=http://tropical.jungle-team.online/utilidades/rsync
DIR_BIN=/usr/bin
RSYNC_FILE=$DIR_BIN/rsync
if [ ! -f $RSYNC_FILE ];
then
    ES_ARM=$(uname -a | grep arm | wc -l)
    if [ "$ES_ARM" -eq 1 ];
    then
        BINARIO=binarios/arm/rsync
    else
        BINARIO=binarios/mipsel/rsync
    fi
    wget $URL/$BINARIO -P $DIR_BIN
    chmod +x $RSYNC_FILE
fi
